repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: local
  hooks:
  - id: local-mypy-check
    name: mypy check
    entry: mypy
    language: system
    types: [text]
    files: "\\.py$"

  - id: local-black-check
    name: black check
    entry: black
    language: system
    types: [text]
    files: "\\.py$"

  - id: local-flake8-check
    name: flake8 check
    entry: flake8
    language: system
    types: [text]
    files: "\\.py$"
